### ISSUE TITLE
Can I edit a template?

### ISSUE THREAD

**Issue by Grantmakers1** [smartergiving/foundation-website-template#8]
I attempted to change the template for [a member's] grants data so that it would display year, name, location, program, purpose, and url. When I simply left information out, the header still appeared, so for instance it was showing name, location, amount, and purpose as the headers, with values of $0 under amount and nothing below anything blank. It did not even show the grantor's [programs] at all. I'm going to build all new grants .csv's since [the member] gave me something totally bizarre that doesn't help at all. If those don't work I'm throwing in the towel on trying to make [their] grants data look different than the generic template.

---

Chad: Edited to remove member's identity

**Comment by chadokruse** [comment]
The ability to customize the CSV template is definitely on the roadmap (see #5).

I've got some ideas on how to handle your immediate needs with the specific member site you mention, so I'll connect with you directly to chat more.
